### PR TITLE
Updating mbed-os to mbed-os-5.4.6

### PR DESCRIPTION
**Pull request by adbridge**
Please test/merge this PR and then tag Master with mbed-os-5.4.6

### CODE REVIEW

**Comment by AlessandroA** [comment]
retest uvisor

**Comment by AlessandroA** [comment]
retest uvisor

**Comment by AlessandroA** [comment]
@adbridge could you please rebase this on top of the latest master? It was updated this morning.

**Comment by adbridge** [comment]
Releases don't come off master they come off the 5.4 release branch. That is the latest release. It will be 2 more weeks before 5.4.7 comes out I'm afraid

**Comment by adbridge** [comment]
Does this mean you will have known issues for this release and uvisor?

**Comment by AlessandroA** [comment]
Sorry @adbridge I meant to rebase this PR (`adbridge:master`) on top of this repository master (`ARMmbed:master`). This way we make sure that the update to mbed OS 5.4.6 happens after our latest changes.

**Comment by adbridge** [comment]
@AlessandroA Ah ok, done. Though your CI is working in a strange way if that is required...

**Comment by AlessandroA** [comment]
Yes the CI was having some issues, but they were not actual test failures. I'll make sure to run it again in case it fails — this PR is expected to go green. Thanks for the update!

**Comment by AlessandroA** [comment]
retest uvisor

**Pull request merged**
