### PR TITLE
Updating mbed-os to mbed-os-5.4.4

### PR DESCRIPTION
**Pull request by 0xc0170**
Please test/merge this PR and then tag Master with mbed-os-5.4.4

### CODE REVIEW

**Comment by AlessandroA** [comment]
@0xc0170 could you please rebase and force-push?

**Comment by 0xc0170** [comment]
Our script failed or in the meantime someone changed mbed-os.lib? (just to be sure the script is fine)

I'll rebase

**Comment by AlessandroA** [comment]
Thanks!

The last change was to update to mbed OS 5.4.3.

**Comment by 0xc0170** [comment]
rebased

**Pull request merged**
