### PR TITLE
Merge Mbed os 5.7.0 oob

### PR DESCRIPTION
**Pull request by MarceloSalazar**
@alzix @adbridge 

Please comment if you see any problem. Thanks.

### CODE REVIEW

**Comment by alzix** [comment]
@MarceloSalazar there is an conflict in mbed-os.lib file.
Could you please resolve it  I'm not sure how did we get this conflict in the first place

**Comment by 0xc0170** [comment]
One note that what we found out this week, gcc arm pushed a new update (version 7) out, so this travis failures are either real errors or related to the update.

We fixed it in mbed-os, to fetch exact version 6 of GCC.

**Pull request merged**
